[options]
admin_passwd = admin
proxy_mode = True
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/usr/lib/python3/dist-packages/addons

db_host = dpg-d7br0redqaus73as2kkg-a.internal
db_port = 5432
db_name = odoo_global
db_user = vibe_odoo_db_user
db_password = 1pzlftiECI121CR5IG1RUmwQ6fQSDDjk

http_port = 8069
http_interface = 0.0.0.0
