[options]
admin_passwd = admin
proxy_mode = True
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/usr/lib/python3/dist-packages/addons

db_host = dpg-d6kqeos50q8c73eaj4fg-a
db_port = 5432
db_name = vibe_odoo_db
db_user = vibe_odoo_db_user
db_password = ld80kbYOX1kXDN5NDti3ER2vvG4urMVD

http_port = 8069
http_interface = 0.0.0.0
